
export const sportsList = [
  'Agilidade canina (Dog agility)',
  'Artistic cycling',
  'Asa-delta',
  'Atletismo',
  'Automobilismo',
  'Badminton',
  'Bandy',
  'Barco-dragão',
  'Base jump',
  'Basquetebol',
  'Beach Tennis',
  'Beisebol',
  'Biathlon',
  'Bike Trial',
  'BMX Freestyle',
  'BMX Racing',
  'Bobsled',
  'Bocha',
  'Bodyboard',
  'Boliche',
  'Boulder',
  'Boxe',
  'Caiaque polo',
  'Canoagem oceânica',
  'Canoagem slalom',
  'Canoagem velocidade',
  'Capoeira',
  'Carom billiards',
  'Cheerleading',
  'Ciclismo de estrada',
  'Ciclismo de pista',
  'Combinado nórdico',
  'Corrida de aventura',
  'Corrida de camelos',
  'Corrida de cavalos',
  'Corrida de montanha / Trail running',
  'Corrida de obstáculos (OCR)',
  'Corrida de rua',
  'Críquete',
  'Croquet',
  'Cross-country running',
  'CrossFit',
  'Curling',
  'Cycle-ball',
  'Cyclo-cross',
  'Dardos',
  'Disc golf',
  'Dodgeball',
  'Drone racing',
  'Duatlo',
  'Enduro off-road (moto)',
  'Escalada esportiva',
  'Escalada no gelo',
  'Esgrima',
  'Esqui alpino',
  'Esqui aquático',
  'Esqui cross-country',
  'Esqui freestyle',
  'Falcoaria competitiva',
  'Fisiculturismo (Bodybuilding)',
  'Floorball',
  'Futebol',
  'Futebol americano',
  'Futebol australiano',
  'Futebol gaélico',
  'Futsal',
  'Ginástica acrobática',
  'Ginástica artística',
  'Ginástica de trampolim',
  'Ginástica rítmica',
  'Golfe',
  'Halterofilismo (Weightlifting)',
  'Handebol',
  'Hipismo (Saltos, Adestramento, CCE)',
  'Hóquei em campo',
  'Hóquei em patins',
  'Hóquei no gelo',
  'Jiu-Jitsu Brasileiro',
  'Judô',
  'Kabaddi',
  'Karate',
  'Kart',
  'Kendo',
  'Kickboxing',
  'Kitesurfe',
  'Korfball',
  'Lacrosse',
  'Luge',
  'Marcha atlética',
  'Mergulho livre (Freediving)',
  'MMA (Artes Marciais Mistas)',
  'Montanhismo / Alpinismo',
  'Motociclismo (velocidade)',
  'Motocross',
  'Mountain bike',
  'Muay Thai',
  'Mushing (trenó com cães)',
  'Nado artístico',
  'Natação (piscina)',
  'Natação em águas abertas',
  'Netball',
  'Padel',
  'Parapente',
  'Paraquedismo',
  'Parkour',
  'Patinação artística',
  'Patinação de velocidade',
  'Patinação de velocidade curta',
  'Pickleball',
  'Platform tennis',
  'Poker esportivo',
  'Polo',
  'Polo aquático',
  'Powerboat racing',
  'Powerlifting',
  'Racquetball',
  'Rali',
  'Remo',
  'Rodeio / Montaria em touro',
  'Rugby League',
  'Rugby Union',
  'Salto de esqui',
  'Saltos ornamentais',
  'Sambo',
  'Savate',
  'Sepak Takraw',
  'Sinuca / Bilhar',
  'Skeleton',
  'Slackline / Highline',
  'Snooker',
  'Snowboard',
  'Softbol',
  'Speedway (moto em pista oval)',
  'Squash',
  'Stand Up Paddle (SUP)',
  'Strongman',
  'Sumô',
  'Surfe',
  'Taekwondo',
  'Tênis',
  'Tênis de mesa',
  'Teqball',
  'Tiro com arco',
  'Tiro esportivo',
  'Triatlo',
  'Vela',
  'Vôlei de praia',
  'Voleibol',
  'Wakeboard',
  'Windsurfe',
  'Wingsuit flying',
  'Wrestling',
  'Xadrez'
].sort();
