
export const sportsList = [
  'Atletismo',
  'Badminton',
  'Basquete',
  'Beach Tennis',
  'Boxe',
  'Calistenia',
  'Canoagem',
  'Capoeira',
  'Ciclismo',
  'Corrida de Rua',
  'Crossfit',
  'Dança (Zumba, FitDance, etc.)',
  'Escalada',
  'Esgrima',
  'Futebol',
  'Futebol Americano',
  'Futevôlei',
  'Futsal',
  'Ginástica Artística',
  'Ginástica Rítmica',
  'Golf',
  'Handebol',
  'Jiu-Jitsu',
  'Judô',
  'Karatê',
  'MMA',
  'Mountain Bike',
  'Muay Thai',
  'Musculação',
  'Nado Sincronizado',
  'Natação',
  'Padel',
  'Peteca',
  'Pilates',
  'Polo Aquático',
  'Remo',
  'Rugby',
  'Skate',
  'Slackline',
  'Stand Up Paddle (SUP)',
  'Surfe',
  'Taekwondo',
  'Tênis',
  'Tênis de Mesa',
  'Tiro com Arco',
  'Ultimate Frisbee',
  'Vôlei',
  'Vôlei de Praia',
  'Xadrez',
  'Yoga'
].sort();
