// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqrplxlmxvqgcaxkertf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxcnBseGxteHZxZ2NheGtlcnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjMwMjksImV4cCI6MjA2NTU5OTAyOX0.7f-LXJ2Ifa2mMEp85-062yq94OEXQZ1qLMi2wSIf_uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});